stages:
    - test

variables:
    GO111MODULE: "on"

.test: &test_template
    stage: test
    script:
        - go mod download
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golangci/golangci-lint:v1.24
    script:
        - go mod download
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.16
    script:
        - go mod download
        - ./script/coverage.sh

go-1.13:
    <<: *test_template
    image: golang:1.13

go-1.14:
    <<: *test_template
    image: golang:1.14

go-1.15:
    <<: *test_template
    image: golang:1.15

go-1.16:
    <<: *test_template
    image: golang:1.16

go-rc:
    <<: *test_template
    image: golang:rc
    allow_failure: true
